server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev
    username: postgres
    password: 0508
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
upload:
  server:
    folder: /Users/hp/OneDrive/Документы/upload/


api:
  json placeholder: https://jsonplaceholder.typicode.com/

jwt:
  token:
    secret: 111111
    validity: 86400000


